colorScheme = "carolina"
logo = "img/icon.png"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 3
  cardView = true

[article]
  showDate = true
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showPagination = true
  showTaxonomies = true
  sharingLinks = ["linkedin", "x-twitter", "whatsapp", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showCards = true
  groupByYear = false

[umamiAnalytics]
  websiteid = "273c4fa3-d3ba-45c7-a4e9-b2aae212af22"
  domain = "cloud.umami.is"
  dataDomains = "carolinafaccin.github.io"
