colorScheme = "carolina"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 3
  cardView = true

[article]
  showDate = true
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showPagination = true
  showTaxonomies = true
  sharingLinks = ["linkedin", "x-twitter", "whatsapp", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showCards = true
  groupByYear = false
